apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: process-supervisor
  name: ps-controller-role
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "list", "get", "patch", "update", "watch" ]
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "list", "get", "update" ]
