apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ps-controller-rolebinding
  namespace: process-supervisor
subjects:
  - kind: ServiceAccount
    name: ps-controller-sa
    namespace: process-supervisor
roleRef:
  kind: Role
  name: ps-controller-role
  apiGroup: rbac.authorization.k8s.io
