apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: process-supervisor-pod-reader
  namespace: process-supervisor
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get" ]
