apiVersion: v1
kind: Service
metadata:
  namespace: process-supervisor
  name: process-supervisor-app-service
  annotations:
    prometheus.io/path: "/metrics"
    prometheus.io/scrape: "true"
    prometheus.io/port: "2112"
spec:
  selector:
    app: process-supervisor-app
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: http
  type: ClusterIP