apiVersion: v1
kind: Service
metadata:
  namespace: processes-supervisor
  name: processes-supervisor-app-service
  # annotations:
  #   prometheus.io/path: "/metrics"
  #   prometheus.io/scrape: "true"
  #   prometheus.io/port: "2112"
spec:
  selector:
    app: processes-supervisor-app
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: http
